### ISSUE TITLE
Error undefined method alias_method_chain

### ISSUE THREAD

**Issue by sechix** [solidusio/solidus_auth_devise#112]
I updated to rails 5.1 and solidus master  but I get this error, I was reading that this could be due to device version, and requires device master.

**Comment by swcraig** [comment]
Hi @sechix,
I believe the problem is that `alias_method_chain` was [removed in Rails 5.1](https://github.com/rails/rails/commit/7c848e6dd493ff236d33a0410a92f4c3e5cc3c7f)

**Comment by jhawthorn** [comment]
I don't think we're using `alias_method_chain` anywhere. Please feel free to file a new issue if I'm wrong.
