### ISSUE TITLE
`devise.user_registrations` key is not the same in the view

### ISSUE THREAD

**Issue by bourroush** [solidusio/solidus_auth_devise#119]
After doing a signup, the `<%= flash_messages %>` are giving me this error
`translation missing: en-US.devise.user_registrations.spree_user.signed_up`

When I look into your `en.yml` file it looks like the `spree_user:` key is not used https://github.com/solidusio/solidus_auth_devise/blob/master/config/locales/en.yml#L37-L41 but it is under `user_passwords`. Could it be a bug on your .yml file ? Thanks !

**Comment by spaghetticode** [comment]
I think you need to provide your own translation for `en-US`, as this gem only includes generic `en` messages.

You can easily do this by copying the file `config/locales/en.yml` from this gem, rename it to `en-US` and change the first root of the yaml content from `en:` to `en-US:`. You can then customize your translations.

**Comment by kennyadsl** [comment]
Seems fixed.
