### ISSUE TITLE
rake task solidus_auth:install:migrations

### ISSUE THREAD

**Issue by nxtbz** [solidusio/solidus_auth_devise#121]
The rake task `solidus_auth:install:migrations` does nothing, no files added, no migrations created.
```
solidus_auth-2.1.0 
railties-5.1.5
rails-5.1.5
````

**Comment by tvdeyen** [comment]
Thanks for reporting could you tell us how do you installed solidus and solidus_auth_devise?
Are the files probably already in `db/migrate`?

**Comment by nxtbz** [comment]
My initial installation included solidus_auth_devise trough the installation as specified by solidus installation instructions.
