### ISSUE TITLE
Any plans to release to RubyGems?

### ISSUE THREAD

**Issue by sbader** [solidusio/solidus_auth_devise#147]
The last release to rubygems was `2.1.0` back in January 2018. There have been a lot of changes to this gem since then (https://github.com/solidusio/solidus_auth_devise/compare/v2.1.0...master).

Are there plans to release to RubyGems again?

**Comment by stem** [comment]
I would like a release as well, so I've prepared a draft for the changelog : 
```
* Add DB index to `reset_password_token` field
* Add missing pessimistic versioning
* Add missing translation to `spree.change_my_password`
* Allow Spree::Admin::UserPasswordsController to be accessed from admin
* Disable backend footer profile edit link if role cannot edit users
* Fix issue with redirections using routes like `new_spree_user_session_url`
* Fix migration `20101026184950` `down` method
* Fix to not reuse spree_current_user as `@user` 
* Replace Spree.t with I18n.t
* Lock mysql2 to 0.4.x
* Lock SQLite3 to version 1.3
* Remove FactoryBot warnings
* Configure CI to ensure support on ruby 2.3 + Solidus 2.4 - 2.8
```

Maybe @kennyadsl, @jacobherrington or @spaghetticode can take it from here ?

BTW, is there a way to ping the core team directly instead of members ?
You're the 3 that popped on my mind but probably not the only 3 who could to this release 😉

**Comment by kennyadsl** [comment]
Thanks, @stem that's very appreciated help. I'm also in favor of releasing a new version.

> BTW, is there a way to ping the core team directly instead of members?

I can do that with @solidusio/core-team, but I think there's no way for people outside the group itself to ping it.

**Comment by kennyadsl** [comment]
[v2.2.0](https://rubygems.org/gems/solidus_auth_devise/versions/2.2.0) has been released today. Let us know if everything works as expected.

**Comment by sbader** [comment]
Awesome, thanks so much!
