### ISSUE TITLE
Spree.user_class not using my specific class

### ISSUE THREAD

**Issue by EmCousin** [solidusio/solidus_auth_devise#169]
Hi,

I'm following the [guidelines](https://guides.solidus.io/developers/users/custom-authentication.html) to set a custom auth system on my app's backend.

I have this line in my `config/initializers/spree.rb` file : 
```ruby
Spree.user_class = 'User'
```
but when booting the app or running the rails console, hitting `Spree.user_class` still returns `Spree::User`.

I believe this is due to [this line](https://github.com/solidusio/solidus_auth_devise/blob/master/lib/spree/auth/engine.rb#L17), that is executed _after loading the initializers_, thus setting `Spree.user_class` back to `Spree::User`.

I've been able to workaround this issue by overriding the related initializer declaration in my main config file:
```ruby
# config/application.rb
initializer "solidus_auth_devise.set_user_class", after: :load_config_initializers do
  Spree.user_class = "User"
end
```

### Questions
- Did I have the wrong interpretation and I could have messed something up in my app?
- Otherwise, should the custom generator instead generate the block I wrote above?

Thanks in advance!

**Comment by marcrohloff** [comment]
I guess I'm just wary of adding code to `initializer.rb` because no one is ever going to look there. Some general thoughts.
* Can we add these lines to `spree.rb` instead?
* We should remove  line 83 from spree.rb` and if necessary add a comment there.

**Comment by kennyadsl** [comment]
Hey @EmCousin, thanks for reporting this issue. It looks a legit bug to me and I'll try to investigate further.

**Comment by kennyadsl** [comment]
@EmCousin can you please give a try to this PR's branch https://github.com/solidusio/solidus_auth_devise/pull/171 and let us know if this fix works?

**Comment by kennyadsl** [comment]
@EmCousin after a second thought, with the help of @tvdeyen, we realized that this extension is meant to be used with the `Spree::User` class. The possibility to change this class is left to users that do not need this extension and have a custom devise installation (or other authentication systems). Can you please provide more information about your use case?

**Comment by EmCousin** [comment]
Hi @kennyadsl, first, thank you for your answers.

About my use case : I plugged the `solidus` gem along with `solidus-reviews`, which requires `solidus-auth-devise` as a dependency, on a Rails app that already has Devise installed.

This installation is rather classic, with a `database_authenticatable` model `User`.

I'm following these [guidelines](https://guides.solidus.io/developers/users/custom-authentication.html) to do so. It works perfectly, except for the `Spree.user_class` step, reason for which I initiated this issue.

Is that information relevant enough?

**Comment by kennyadsl** [comment]
Sure, thanks for the detailed explanation. 

I think the issue here is with `solidus_reviews`, it should not be dependant on `solidus_auth_devise`.

**Comment by kennyadsl** [comment]
I'm having a look at that gem right now to see if we can get read of the `solidus_auth_devise` dependency and release a new version. I'll keep you posted.

**Comment by kennyadsl** [comment]
I've opened https://github.com/solidusio-contrib/solidus_reviews/pull/53 which should allow you to use the extension without `solidus_auth_devise`. When it will be merged, we'll release a new version of `solidus_reviews` that you can use.
