### ISSUE TITLE
Rails 6, Production only issue, works fine in dev, tripped up assets:precompile build process on Heroku, compiled fine locally.

### ISSUE THREAD

**Issue by stevenkolstad** [solidusio/solidus_auth_devise#175]
/app/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.1.10/lib/zeitwerk/loader/callbacks.rb:17:in `on_file_autoloaded': expected file /app/vendor/bundle/ruby/2.6.0/gems/solidus_auth_devise-2.3.0/lib/controllers/backend/spree/admin/orders/customer_details_controller_decorator.rb to define constant Spree::Admin::Orders::CustomerDetailsControllerDecorator, but didn't (NameError)

**Comment by kennyadsl** [comment]
I think this is a duplicate of https://github.com/solidusio/solidus_auth_devise/issues/174 - thanks for reporting anyway!

**Comment by stevenkolstad** [comment]
Of course, you're right. Thank you!
