### ISSUE TITLE
Cant locate devise.rb file to locate secret key.

### ISSUE THREAD

**Issue by jeffgvegas** [solidusio/solidus_auth_devise#188]
Hi guys I am brand new to programming and im working on creating a new solidus project. It doesnt seem to create this devise.rb file that contains the secret key. If it does I cant seem to find it. Maybe we could create a pull request to update the documentation on how to easily access this?

**Comment by kennyadsl** [comment]
Hey there! Can you please share the steps you made to install solidus and solidus_auth_devise?

**Comment by Taikon** [comment]
can we close this issue?

**Comment by aldesantis** [comment]
Yep, I think we can. Thanks for bringing it to our attention!
