### ISSUE TITLE
Latest release on GitHub is out of date

### ISSUE THREAD

**Issue by bbuchalter** [solidusio/solidus_auth_devise#53]
https://github.com/solidusio/solidus_auth_devise/releases shows v1.2 as the latest release but https://rubygems.org/gems/solidus_auth_devise shows it as v1.4

**Comment by stewart** [comment]
There's a hidden-ish little tab there to "Show X newer tags" - 1.2 was the only release for which a GitHub release note was drafted.

I don't think they serve much purpose for smaller-ish projects like `solidus_auth_devise`, but they may be investigated for further releases.
