### ISSUE TITLE
No CHANGELOG for this repo

### ISSUE THREAD

**Issue by bbuchalter** [solidusio/solidus_auth_devise#54]
It's time to start a changelog file on this repo for each release. Perhaps we could backfill it between v1.1 and the latest release for v1.4?

**Comment by stewart** [comment]
Added, as of https://github.com/solidusio/solidus_auth_devise/commit/a236e8b721dfe5c7ccda38e62d548eb6c3bd7ce8. Thanks for the suggestion!.

**Comment by bbuchalter** [comment]
Thank you!
