### ISSUE TITLE
Latest release broke compatibility with solidus_social

### ISSUE THREAD

**Issue by jarednorman** [solidusio/solidus_auth_devise#70]
Not sure which gem needs a fix because I haven't found the problem yet.

**Comment by jarednorman** [comment]
I'm suspecting it has something to do with the major bump to Devise.

**Comment by jhawthorn** [comment]
If solidus_social is incompatible with the latest devise that should be declared there. I also don't think the issues there are related to devise or solidus_auth_devise.
