### ISSUE TITLE
db index on reset_password_token missing

### ISSUE THREAD

**Issue by vfonic** [solidusio/solidus_auth_devise#83]
The `reset_password_token` db index has been existing in devise since the creation of this file:
https://github.com/plataformatec/devise/blob/88724e10adaf9ffd1d8dbfbaadda2b9d40de756a/lib/generators/active_record/templates/migration.rb#L14

It's a minor fix, not really sure it will speed things up (because every index slows insert/update)

**Comment by kennyadsl** [comment]
This is closed with #140
